application: html5voodoo
version: 1
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /proto
  script: proto.php

- url: /.*
  script: index.html

skip_files:
- ^(.*/)?.*js/hvdoo/.*
