application: html5voodoo
version: 1
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /sound
  static_dir: sound

- url: /js
  static_dir: js

- url: /proto
  script: proto/index.php

- url: /tetris
  script: tetris/index.html

- url: /rain
  script: rain.html

- url: /angularjs-terrible-performance
  script: angularjs-terrible-performance.html

- url: /.*
  script: index.html

skip_files:
- ^(.*/)?.*js/hvdoo/.*
